#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["requests", "pyyaml"]
# ///
"""
COROS Training Plan Pusher.

Parses a weekly training plan Markdown (generated by training-weekly skill)
and pushes each day's running workout to COROS Training Hub, where it syncs
to the user's COROS watch.

Usage:
  # Push workouts from a weekly plan file
  python coros_push_plan.py Runner_A_W3_训练计划.md

  # Dry-run (parse and show what would be pushed, no API calls)
  python coros_push_plan.py Runner_A_W3_训练计划.md --dry-run

  # Push specific days only
  python coros_push_plan.py Runner_A_W3_训练计划.md --days 3,6

  # Use explicit token instead of .env
  python coros_push_plan.py Runner_A_W3_训练计划.md --token <TOKEN>

Workflow:
  1. Parse Markdown → extract each day's training type, distance, pace, structure
  2. Map to COROS workout segments (warmup / main / intervals / cooldown)
  3. Call /training/program/calculate → /training/program/add for each workout
  4. Report results (program IDs, training load, etc.)

Supported training types:
  - 轻松跑 / 恢复跑 / Easy Run → warmup + main(E-pace) + cooldown
  - 节奏跑 / Tempo Run → warmup + main(T-pace) + cooldown
  - 间歇 / Interval → warmup + N×(fast+recovery) + cooldown
  - 长距离 / Long Run / LSD → warmup + main(E-pace) + cooldown
  - 休息 / 交叉训练 → skipped (no COROS workout)

References:
  - API pattern: github.com/rowlando/coros-workout-mcp (strength workouts)
  - Running payload: github.com/Taerc-DUO/skill--openclaw-coros-coach
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from coros_client import CorosClient, format_pace, format_duration


# ── Data Models ────────────────────────────────────────────────────

@dataclass
class RunSegment:
    """A single segment of a running workout."""
    role: str           # 'warmup', 'main', 'cooldown', 'fast', 'recovery'
    distance_km: float
    pace_sec: int       # seconds per km
    pace_max_sec: int = 0
    display_name: str = ""

    def __post_init__(self):
        if not self.pace_max_sec:
            self.pace_max_sec = self.pace_sec + 10
        if not self.display_name:
            names = {
                "warmup": "热身", "cooldown": "放松", "main": "训练",
                "fast": "快跑", "recovery": "慢跑",
            }
            self.display_name = names.get(self.role, "训练")


@dataclass
class DailyWorkout:
    """Parsed daily training prescription."""
    day_number: int             # 1-7 (Mon-Sun)
    weekday: str                # 周一..周日
    date: str                   # YYYY-MM-DD
    training_type: str          # 轻松跑, 节奏跑, 间歇, 长距离, 休息, etc.
    total_distance_km: float = 0.0
    pace_str: str = ""          # e.g. "5'30"/km"
    pace_sec: int = 0
    pace_max_sec: int = 0
    training_desc: str = ""     # full training description
    hr_cap: int = 0
    rpe: int = 0
    segments: list[RunSegment] = field(default_factory=list)
    skip: bool = False          # True for rest/cross-training days
    skip_reason: str = ""

    @property
    def coros_name(self) -> str:
        """Generate COROS workout name."""
        type_abbr = {
            "轻松跑": "E跑", "恢复跑": "E跑", "长距离": "LSD",
            "节奏跑": "T跑", "间歇": "I跑", "间歇跑": "I跑",
        }
        abbr = type_abbr.get(self.training_type, self.training_type)
        dist = f"{self.total_distance_km:.0f}km" if self.total_distance_km else ""
        return f"{self.weekday} {abbr} {dist}".strip()

    @property
    def coros_overview(self) -> str:
        """Generate COROS workout description."""
        parts = []
        for seg in self.segments:
            dist = f"{seg.distance_km:.1f}km" if seg.distance_km else ""
            pace = format_pace(seg.pace_sec)
            parts.append(f"{seg.display_name} {dist}@{pace}")
        return " → ".join(parts) if parts else self.training_desc[:100]


# ── Pace Parsing ───────────────────────────────────────────────────

def parse_pace(pace_str: str) -> int:
    """Parse pace string to seconds per km.

    Handles: "5'30\"/km", "5'30\"", "5:30/km", "5:30", "330"
    Returns 0 if unparseable.
    """
    if not pace_str:
        return 0
    pace_str = pace_str.strip()
    # Raw seconds
    if re.fullmatch(r"\d+", pace_str):
        return int(pace_str)
    # M'SS or M:SS patterns
    m = re.search(r"(\d+)\s*[''′:]\s*(\d{1,2})", pace_str)
    if m:
        return int(m.group(1)) * 60 + int(m.group(2))
    return 0


def parse_pace_range(pace_str: str) -> tuple[int, int]:
    """Parse pace range like "5'20\"-5'40\"/km" or single pace.

    Returns (pace_min_sec, pace_max_sec). min = faster, max = slower.
    """
    if not pace_str:
        return 0, 0
    # Range pattern: "X'XX" - Y'YY" or "X'XX"~Y'YY" or "X'XX"-Y'YY"
    parts = re.split(r'[\s]*[-–~至到][\s]*', pace_str, maxsplit=1)
    if len(parts) == 2:
        p1 = parse_pace(parts[0])
        p2 = parse_pace(parts[1])
        if p1 and p2:
            return (min(p1, p2), max(p1, p2))
    p = parse_pace(pace_str)
    return (p, p + 10) if p else (0, 0)


# ── Markdown Parser ────────────────────────────────────────────────

def parse_weekly_plan(md_path: str) -> list[DailyWorkout]:
    """Parse a weekly training plan Markdown file.

    Extracts Day 1-7 training prescriptions from the standard format
    generated by training-weekly skill.

    Args:
        md_path: Path to the *_W*_训练计划.md file.

    Returns:
        List of 7 DailyWorkout objects (some may have skip=True).
    """
    text = Path(md_path).read_text(encoding="utf-8")
    workouts: list[DailyWorkout] = []

    # Split into daily sections by "### Day N:" headers
    day_pattern = re.compile(
        r'^###\s+Day\s+(\d+)\s*[:：]\s*(周[一二三四五六日])\s+'
        r'(\d{4}-\d{2}-\d{2})\s*[—–-]\s*(.+?)$',
        re.MULTILINE,
    )
    matches = list(day_pattern.finditer(text))

    for i, match in enumerate(matches):
        day_num = int(match.group(1))
        weekday = match.group(2)
        date = match.group(3)
        training_type = match.group(4).strip()

        # Extract section text until next Day header or end
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        section = text[start:end]

        workout = DailyWorkout(
            day_number=day_num,
            weekday=weekday,
            date=date,
            training_type=training_type,
        )

        # Check if rest / cross-training day
        rest_keywords = ["休息", "完全休息", "交叉训练", "瑜伽", "游泳", "骑车"]
        if any(kw in training_type for kw in rest_keywords):
            workout.skip = True
            workout.skip_reason = training_type
            workouts.append(workout)
            continue

        # Parse table rows for structured fields
        _parse_table_fields(section, workout)

        # Build COROS segments from parsed data
        _build_segments(workout)

        workouts.append(workout)

    return workouts


def _parse_table_fields(section: str, workout: DailyWorkout) -> None:
    """Extract fields from the daily training table."""
    table_row = re.compile(
        r'^\|\s*\*{0,2}(.+?)\*{0,2}\s*\|\s*(.+?)\s*\|',
        re.MULTILINE,
    )
    for m in table_row.finditer(section):
        key = m.group(1).strip().strip("*")
        val = m.group(2).strip()

        if key == "类型":
            if not workout.training_type or workout.training_type == val:
                workout.training_type = val
        elif key == "训练":
            workout.training_desc = val
        elif key == "距离":
            dist_m = re.search(r'([\d.]+)\s*km', val)
            if dist_m:
                workout.total_distance_km = float(dist_m.group(1))
        elif key == "配速":
            workout.pace_str = val
            p_min, p_max = parse_pace_range(val)
            workout.pace_sec = p_min
            workout.pace_max_sec = p_max
        elif key == "心率":
            hr_m = re.search(r'(\d+)\s*bpm', val)
            if hr_m:
                workout.hr_cap = int(hr_m.group(1))
        elif key == "RPE":
            rpe_m = re.search(r'(\d+)', val)
            if rpe_m:
                workout.rpe = int(rpe_m.group(1))


def _build_segments(workout: DailyWorkout) -> None:
    """Build COROS running segments from the parsed workout data."""
    if workout.skip or workout.total_distance_km <= 0:
        workout.skip = True
        workout.skip_reason = workout.skip_reason or "无跑步距离"
        return

    if not workout.pace_sec:
        workout.skip = True
        workout.skip_reason = "无法解析配速"
        return

    tt = workout.training_type

    # Detection order: easy/long first (most common), then interval, then tempo
    if _is_easy_or_long(tt, workout.training_desc):
        _build_easy_segments(workout)
    elif _is_interval(tt, workout.training_desc):
        _build_interval_segments(workout)
    elif _is_tempo(tt, workout.training_desc):
        _build_tempo_segments(workout)
    else:
        # Default: treat as easy run
        _build_easy_segments(workout)


def _is_easy_or_long(training_type: str, desc: str) -> bool:
    """Detect easy/recovery/long runs (highest priority — most common)."""
    type_lower = training_type.lower()
    easy_keywords = [
        "轻松跑", "恢复跑", "easy", "recovery", "长距离", "long",
        "lsd", "慢跑", "有氧跑", "大步跑",
    ]
    return any(kw in type_lower for kw in easy_keywords)


def _is_interval(training_type: str, desc: str) -> bool:
    keywords = ["间歇", "interval", "亚索", "yasso", "变速", "fartlek"]
    combined = (training_type + " " + desc).lower()
    return any(kw in combined for kw in keywords)


def _is_tempo(training_type: str, desc: str) -> bool:
    """Detect tempo runs. Checks type strictly (desc may contain '节奏' in other contexts)."""
    keywords = ["节奏跑", "tempo", "乳酸阈", "threshold", "巡航间歇"]
    type_lower = training_type.lower()
    return any(kw in type_lower for kw in keywords)


def _build_easy_segments(workout: DailyWorkout) -> None:
    """Build warmup + main + cooldown for easy/long runs."""
    total = workout.total_distance_km
    pace = workout.pace_sec
    pace_max = workout.pace_max_sec

    if total <= 4:
        # Short run: single main segment, no warmup/cooldown
        workout.segments = [
            RunSegment("main", total, pace, pace_max, "训练"),
        ]
    else:
        # Standard: 1km warmup (slower) + main + 1km cooldown (slower)
        warmup_km = 1.0
        cooldown_km = 1.0
        main_km = total - warmup_km - cooldown_km

        warmup_pace = pace + 20  # ~20s/km slower
        cooldown_pace = pace + 30

        workout.segments = [
            RunSegment("warmup", warmup_km, warmup_pace, warmup_pace + 10, "热身"),
            RunSegment("main", main_km, pace, pace_max, "训练"),
            RunSegment("cooldown", cooldown_km, cooldown_pace, cooldown_pace + 10, "放松"),
        ]


def _build_tempo_segments(workout: DailyWorkout) -> None:
    """Build warmup + tempo main + cooldown for tempo runs."""
    total = workout.total_distance_km
    pace = workout.pace_sec
    pace_max = workout.pace_max_sec

    # Try to parse structured description: "热身 Xkm → 主课 Ykm @ T-Pace → 冷身 Zkm"
    desc = workout.training_desc
    struct_m = re.search(
        r'热身\s*([\d.]+)\s*km.*?'
        r'(?:主课|节奏|T[- ]?Pace)\s*([\d.]+)\s*km.*?'
        r'(?:冷身|放松)\s*([\d.]+)\s*km',
        desc, re.IGNORECASE,
    )
    if struct_m:
        warmup_km = float(struct_m.group(1))
        main_km = float(struct_m.group(2))
        cooldown_km = float(struct_m.group(3))
    else:
        warmup_km = min(2.0, total * 0.2)
        cooldown_km = min(2.0, total * 0.2)
        main_km = total - warmup_km - cooldown_km

    e_pace = pace + 60  # E-pace ~60s slower than T-pace

    workout.segments = [
        RunSegment("warmup", warmup_km, e_pace, e_pace + 10, "热身"),
        RunSegment("main", main_km, pace, pace_max, "节奏跑"),
        RunSegment("cooldown", cooldown_km, e_pace + 10, e_pace + 20, "放松"),
    ]


def _build_interval_segments(workout: DailyWorkout) -> None:
    """Build warmup + N×(fast+recovery) + cooldown for interval workouts."""
    total = workout.total_distance_km
    pace = workout.pace_sec
    desc = workout.training_desc

    # Try to parse interval structure from description
    # Patterns: "N × Xm", "N × X.Xkm", "NxXm", "400m×6-8组"
    rep_m = re.search(
        r'(\d+)\s*[×xX]\s*([\d.]+)\s*(m|km)', desc, re.IGNORECASE,
    )
    reps = 0
    rep_dist_km = 0.0
    if rep_m:
        reps = int(rep_m.group(1))
        dist_val = float(rep_m.group(2))
        unit = rep_m.group(3).lower()
        rep_dist_km = dist_val if unit == "km" else dist_val / 1000
    elif re.search(r'([\d.]+)\s*(m|km)\s*[×xX]\s*(\d+)', desc, re.IGNORECASE):
        alt_m = re.search(
            r'([\d.]+)\s*(m|km)\s*[×xX]\s*(\d+)', desc, re.IGNORECASE)
        dist_val = float(alt_m.group(1))
        unit = alt_m.group(2).lower()
        reps = int(alt_m.group(3))
        rep_dist_km = dist_val if unit == "km" else dist_val / 1000

    if not reps or not rep_dist_km:
        # Fallback: treat as tempo run if can't parse interval structure
        _build_tempo_segments(workout)
        return

    # Parse recovery distance (default: equal to rep distance for short, half for long)
    recovery_dist_km = rep_dist_km if rep_dist_km <= 0.5 else rep_dist_km * 0.5

    # Calculate warmup/cooldown
    interval_total = reps * (rep_dist_km + recovery_dist_km)
    remaining = total - interval_total
    warmup_km = max(1.0, remaining * 0.5)
    cooldown_km = max(1.0, remaining - warmup_km)

    # E-pace for warmup/cooldown/recovery (~60s slower than I-pace)
    e_pace = pace + 80

    segments = [
        RunSegment("warmup", warmup_km, e_pace, e_pace + 10, "热身"),
    ]

    for i in range(reps):
        segments.append(
            RunSegment("fast", rep_dist_km, pace, pace + 5, "快跑")
        )
        # No recovery after last rep
        if i < reps - 1:
            segments.append(
                RunSegment("recovery", recovery_dist_km, e_pace, e_pace + 20, "慢跑")
            )

    segments.append(
        RunSegment("cooldown", cooldown_km, e_pace + 10, e_pace + 20, "放松")
    )

    workout.segments = segments


# ── COROS Push Logic ───────────────────────────────────────────────

def push_workout(client: CorosClient, workout: DailyWorkout) -> dict:
    """Push a single daily workout to COROS Training Hub.

    Args:
        client: Authenticated CorosClient.
        workout: Parsed daily workout with segments.

    Returns:
        Result dict with program_id, duration, training_load.
    """
    segments = []
    for i, seg in enumerate(workout.segments, start=1):
        template_key = {
            "warmup": "warmup",
            "cooldown": "cooldown",
        }.get(seg.role, "main")

        coros_seg = CorosClient.build_running_segment(
            template_key=template_key,
            distance_km=seg.distance_km,
            pace_sec=seg.pace_sec,
            pace_max_sec=seg.pace_max_sec,
            sort_index=i,
            display_name=seg.display_name,
            user_id=int(client.user_id or 0),
        )
        segments.append(coros_seg)

    return client.create_running_workout(
        name=workout.coros_name,
        overview=workout.coros_overview,
        segments=segments,
    )


def push_weekly_plan(
    client: CorosClient,
    workouts: list[DailyWorkout],
    days_filter: list[int] | None = None,
    dry_run: bool = False,
) -> list[dict]:
    """Push all workouts from a weekly plan.

    Args:
        client: Authenticated CorosClient.
        workouts: List of 7 DailyWorkout objects.
        days_filter: Optional list of day numbers to push (1-7).
        dry_run: If True, only print what would be pushed.

    Returns:
        List of result dicts for pushed workouts.
    """
    results = []

    for w in workouts:
        if days_filter and w.day_number not in days_filter:
            continue

        if w.skip:
            print(f"  ⏭  Day {w.day_number} {w.weekday} {w.date}: "
                  f"跳过 — {w.skip_reason}", file=sys.stderr)
            results.append({
                "day": w.day_number, "weekday": w.weekday, "date": w.date,
                "status": "skipped", "reason": w.skip_reason,
            })
            continue

        seg_desc = " → ".join(
            f"{s.display_name} {s.distance_km:.1f}km@{format_pace(s.pace_sec)}"
            for s in w.segments
        )
        print(f"  📋 Day {w.day_number} {w.weekday} {w.date}: "
              f"{w.coros_name}", file=sys.stderr)
        print(f"     {seg_desc}", file=sys.stderr)

        if dry_run:
            results.append({
                "day": w.day_number, "weekday": w.weekday, "date": w.date,
                "status": "dry_run", "name": w.coros_name,
                "segments": len(w.segments),
                "total_km": w.total_distance_km,
            })
            continue

        try:
            result = push_workout(client, w)
            dur_min = round(result.get("duration", 0) / 60)
            tl = result.get("training_load", 0)
            print(f"     ✅ 已创建 | ~{dur_min}min | TL={tl} | "
                  f"ID={result.get('program_id', '?')}", file=sys.stderr)
            results.append({
                "day": w.day_number, "weekday": w.weekday, "date": w.date,
                "status": "created", "name": w.coros_name, **result,
            })
        except Exception as e:
            print(f"     ❌ 失败: {e}", file=sys.stderr)
            results.append({
                "day": w.day_number, "weekday": w.weekday, "date": w.date,
                "status": "error", "error": str(e),
            })

    return results


# ── Summary Report ─────────────────────────────────────────────────

def print_summary(results: list[dict]) -> None:
    """Print a summary of push results."""
    created = [r for r in results if r["status"] == "created"]
    skipped = [r for r in results if r["status"] == "skipped"]
    errors = [r for r in results if r["status"] == "error"]
    dry = [r for r in results if r["status"] == "dry_run"]

    print(f"\n{'='*50}", file=sys.stderr)
    print(f"  COROS 课程推送结果", file=sys.stderr)
    print(f"{'='*50}", file=sys.stderr)

    if dry:
        print(f"  [DRY RUN] 将推送 {len(dry)} 个课程", file=sys.stderr)
    if created:
        total_tl = sum(r.get("training_load", 0) for r in created)
        print(f"  ✅ 创建成功: {len(created)} 个课程 (总TL={total_tl})",
              file=sys.stderr)
    if skipped:
        print(f"  ⏭  跳过: {len(skipped)} 天 (休息/交叉训练)",
              file=sys.stderr)
    if errors:
        print(f"  ❌ 失败: {len(errors)} 个", file=sys.stderr)
        for r in errors:
            print(f"     Day {r['day']}: {r['error']}", file=sys.stderr)

    if created:
        print(f"\n  📱 课程已同步到课程库。请在 COROS App 中：",
              file=sys.stderr)
        print(f"     1. 打开「训练课程」", file=sys.stderr)
        print(f"     2. 将各课程拖拽到日历对应日期", file=sys.stderr)
        print(f"     3. 手表同步后自动出现", file=sys.stderr)
    print(f"{'='*50}\n", file=sys.stderr)


# ── CLI ────────────────────────────────────────────────────────────

def resolve_token(args) -> str | None:
    """Resolve COROS token from args, env, or token manager."""
    if args.token:
        return args.token
    token = os.environ.get("COROS_TOKEN")
    if token:
        return token
    try:
        from coros_token_manager import get_valid_token
        user = getattr(args, "user", None)
        return get_valid_token(region=args.region, user=user)
    except Exception:
        return None


def main():
    parser = argparse.ArgumentParser(
        description="COROS 周训练课程推送工具 — 解析训练计划 Markdown 并推送到手表",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "plan_file",
        help="训练计划 Markdown 文件路径 (*_W*_训练计划.md)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="仅解析并显示将要推送的课程，不实际调用 API",
    )
    parser.add_argument(
        "--days", type=str, default="",
        help="只推送指定天数 (逗号分隔, 如 --days 3,6)",
    )

    auth = parser.add_argument_group("COROS 认证")
    auth.add_argument("--user", "-u",
                      help="用户标识 (如 runner_a, runner_b)，用于多用户 token 管理")
    auth.add_argument("--token", help="COROS accessToken")
    auth.add_argument("--email", help="COROS 账号")
    auth.add_argument("--password", help="COROS 密码")
    auth.add_argument(
        "--region", choices=["cn", "intl"], default="cn",
        help="API 区域 (默认: cn)",
    )

    args = parser.parse_args()

    # Validate plan file
    plan_path = Path(args.plan_file)
    if not plan_path.exists():
        print(f"错误: 文件不存在: {plan_path}", file=sys.stderr)
        sys.exit(1)

    # Parse days filter
    days_filter = None
    if args.days:
        try:
            days_filter = [int(d.strip()) for d in args.days.split(",")]
        except ValueError:
            print("错误: --days 格式无效, 使用逗号分隔数字 (如 3,6)",
                  file=sys.stderr)
            sys.exit(1)

    # Parse the plan
    print(f"📖 解析训练计划: {plan_path.name}", file=sys.stderr)
    workouts = parse_weekly_plan(str(plan_path))

    if not workouts:
        print("错误: 未能解析到任何训练日", file=sys.stderr)
        sys.exit(1)

    print(f"   找到 {len(workouts)} 个训练日\n", file=sys.stderr)

    # Dry-run mode: no auth needed
    if args.dry_run:
        results = push_weekly_plan(
            client=None, workouts=workouts,
            days_filter=days_filter, dry_run=True,
        )
        print_summary(results)
        return

    # Load .env if present
    env_path = Path(__file__).parent / ".env"
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                os.environ.setdefault(k.strip(), v.strip())

    # Authenticate
    client = CorosClient(region=args.region)

    if args.token:
        client.set_token(args.token)
    elif args.email and args.password:
        client.login(args.email, args.password)
    else:
        token = resolve_token(args)
        if token:
            client.set_token(token)
        else:
            print("错误: 需要 --token 或 --email + --password\n"
                  "或在 .env 中设置 COROS_TOKEN / COROS_EMAIL + COROS_PASSWORD",
                  file=sys.stderr)
            sys.exit(1)

    # Ensure we have user_id for write operations
    if not client.user_id:
        email = args.email or os.environ.get("COROS_EMAIL")
        password = args.password or os.environ.get("COROS_PASSWORD")
        if email and password:
            print("正在登录以获取 userId...", file=sys.stderr)
            client.login(email, password)
        else:
            print("警告: 无 userId, 写入操作可能失败。"
                  "建议使用 --email + --password 或在 .env 中配置。",
                  file=sys.stderr)

    # Push workouts
    print(f"🚀 开始推送到 COROS Training Hub...\n", file=sys.stderr)
    results = push_weekly_plan(
        client=client, workouts=workouts,
        days_filter=days_filter, dry_run=False,
    )
    print_summary(results)

    # Exit with error code if any failures
    errors = [r for r in results if r["status"] == "error"]
    if errors:
        sys.exit(1)


if __name__ == "__main__":
    main()
